# -*- coding: utf-8 -*-
"""build_feed.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aKEEpj4VktA2bYp4CdpMRCA1xc0cDEl2
"""

import feedgen.feed, pathlib, datetime

fg = feedgen.feed.FeedGenerator()
fg.load_extension('podcast')

fg.title("Daily AI-in-Marketing Brief")
fg.link(href="https://yourname.github.io/marketing-ai-podcaster/feed.xml")
fg.language("en")

for mp3 in sorted(pathlib.Path("audio").glob("*.wav"))[-5:]:
    fe = fg.add_entry()
    fe.id(mp3.stem)
    fe.title(mp3.stem)
    fe.enclosure(url="https://yourname.github.io/marketing-ai-podcaster/audio/"+mp3.name,
                 length=str(mp3.stat().st_size), type="audio/wav")
    fe.published(datetime.datetime.utcnow())

fg.rss_file("feed.xml")