# -*- coding: utf-8 -*-
"""fetch.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aKEEpj4VktA2bYp4CdpMRCA1xc0cDEl2
"""

import feedparser, json, datetime, hashlib, pathlib

SOURCES = [
    "https://news.google.com/rss/search?q=llm+marketing",
    "https://news.google.com/rss/search?q=ai+agents+marketing"
]

today = datetime.date.today().isoformat()
out_dir = pathlib.Path("data")/today; out_dir.mkdir(parents=True, exist_ok=True)

for src in SOURCES:
    for entry in feedparser.parse(src).entries:
        uid = hashlib.md5(entry.link.encode()).hexdigest()[:12]
        path = out_dir/f"{uid}.json"
        if path.exists(): continue
        json.dump({"title":entry.title, "link":entry.link}, path.open("w"))