# -*- coding: utf-8 -*-
"""summarize.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aKEEpj4VktA2bYp4CdpMRCA1xc0cDEl2
"""

import json, pathlib, subprocess, textwrap, os

model = "llama3"
template = (
    "Summarize the following article in <150 words. "
    "Focus on marketing use-cases of LLMs/AI agents and note any metrics or business outcomes.\n\n"
    "{content}"
)
def summarize(url):
    raw = subprocess.check_output(["lynx", "-dump", "-nolist", url]).decode()
    prompt = template.format(content=raw[:8000])   # keep under context limit
    out = subprocess.check_output(["ollama", "run", model, prompt]).decode()
    return textwrap.dedent(out).strip()

for f in pathlib.Path("data").rglob("*.json"):
    meta = json.load(f.open())
    txt = summarize(meta["link"])
    out = f.with_suffix(".md"); out.write_text("# "+meta["title"]+"\n\n"+txt)