# -*- coding: utf-8 -*-
"""tts.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aKEEpj4VktA2bYp4CdpMRCA1xc0cDEl2
"""

from TTS.api import TTS
import pathlib, datetime, hashlib

tts = TTS(model_name="tts_models/en/vctk/vits", progress_bar=False, gpu=False)

today = datetime.date.today().isoformat()
audio_dir = pathlib.Path("audio"); audio_dir.mkdir(exist_ok=True)

for md in pathlib.Path("data", today).glob("*.md"):
    text = md.read_text()
    wav_path = audio_dir / (md.stem + ".wav")
    if wav_path.exists(): continue
    tts.tts_to_file(text, speaker_wav=None, file_path=str(wav_path))