name: Daily marketing-AI podcast
on:
  schedule:
    - cron:  "15 13 * * *"   # ≈06:15 PST daily
  workflow_dispatch:        # lets you run it on demand
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 25
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with: { python-version: '3.11' }

    - name: Install deps
      run: |
        sudo apt-get update && sudo apt-get install -y lynx
        pip install feedparser feedgen transformers sentencepiece accelerate \
                    git+https://github.com/coqui-ai/TTS.git

    - name: Run pipeline
      run: |
        python scripts/fetch.py
        python scripts/summarize.py
        python scripts/tts.py
        python scripts/build_feed.py

    - name: Commit & push
      run: |
        git config user.name  "bot"
        git config user.email "bot@example.com"
        git add audio feed.xml data
        git commit -m "daily update $(date -u '+%F')" || true
        git push

    - name: Send e-mail
      uses: dawidd6/action-send-mail@v5
      with:
        server_address: smtp.gmail.com
        server_port: 587
        username: ${{ secrets.SMTP_USER }}
        password: ${{ secrets.SMTP_PASS }}
        subject: "🎙️ New AI-in-Marketing episode $(date -u '+%F')"
        body: |
          Your episode is live: https://yourname.github.io/marketing-ai-podcaster/feed.xml
        to:  you@example.com
        from: bot@yourdomain.com
